
export const states = [
  { name: 'Andaman and Nicobar Islands', state_code: 'AN' },
  { name: 'Andhra Pradesh', state_code: 'AP' },
  { name: 'Arunachal Pradesh', state_code: 'AR' },
  { name: 'Assam', state_code: 'AS' },
  { name: 'Bihar', state_code: 'BR' },
  { name: 'Chandigarh', state_code: 'CH' },
  { name: 'Chhattisgarh', state_code: 'CT' },
  { name: 'Dadra and Nagar Haveli and Daman and Diu', state_code: 'DH' },
  { name: 'Delhi', state_code: 'DL' },
  { name: 'Goa', state_code: 'GA' },
  { name: 'Gujarat', state_code: 'GJ' },
  { name: 'Haryana', state_code: 'HR' },
  { name: 'Himachal Pradesh', state_code: 'HP' },
  { name: 'Jammu and Kashmir', state_code: 'JK' },
  { name: 'Jharkhand', state_code: 'JH' },
  { name: 'Karnataka', state_code: 'KA' },
  { name: 'Kerala', state_code: 'KL' },
  { name: 'Ladakh', state_code: 'LA' },
  { name: 'Lakshadweep', state_code: 'LD' },
  { name: 'Madhya Pradesh', state_code: 'MP' },
  { name: 'Maharashtra', state_code: 'MH' },
  { name: 'Manipur', state_code: 'MN' },
  { name: 'Meghalaya', state_code: 'ML' },
  { name: 'Mizoram', state_code: 'MZ' },
  { name: 'Nagaland', state_code: 'NL' },
  { name: 'Odisha', state_code: 'OR' },
  { name: 'Puducherry', state_code: 'PY' },
  { name: 'Punjab', state_code: 'PB' },
  { name: 'Rajasthan', state_code: 'RJ' },
  { name: 'Sikkim', state_code: 'SK' },
  { name: 'Tamil Nadu', state_code: 'TN' },
  { name: 'Telangana', state_code: 'TG' },
  { name: 'Tripura', state_code: 'TR' },
  { name: 'Uttar Pradesh', state_code: 'UP' },
  { name: 'Uttarakhand', state_code: 'UT' },
  { name: 'West Bengal', state_code: 'WB' },
];

export const cities: Record<string, string[]> = {
    AN: ["Port Blair"],
    AP: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati"],
    AR: ["Itanagar", "Naharlagun"],
    AS: ["Guwahati", "Dibrugarh", "Silchar", "Jorhat"],
    BR: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"],
    CH: ["Chandigarh"],
    CT: ["Raipur", "Bhilai", "Bilaspur", "Korba"],
    DH: ["Daman", "Silvassa"],
    DL: ["New Delhi", "Delhi"],
    GA: ["Panaji", "Vasco da Gama", "Margao"],
    GJ: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
    HR: ["Faridabad", "Gurugram", "Panipat", "Ambala", "Karnal"],
    HP: ["Shimla", "Solan", "Dharamshala", "Kullu"],
    JK: ["Srinagar", "Jammu", "Anantnag"],
    JH: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro Steel City"],
    KA: ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi-Dharwad", "Belagavi"],
    KL: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
    LA: ["Leh", "Kargil"],
    LD: ["Kavaratti"],
    MP: ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"],
    MH: ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad"],
    MN: ["Imphal"],
    ML: ["Shillong", "Tura"],
    MZ: ["Aizawl", "Lunglei"],
    NL: ["Kohima", "Dimapur"],
    OR: ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Sambalpur"],
    PY: ["Puducherry", "Karaikal"],
    PB: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"],
    RJ: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur"],
    SK: ["Gangtok", "Namchi"],
    TN: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli"],
    TG: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam"],
    TR: ["Agartala"],
    UP: ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Prayagraj"],
    UT: ["Dehradun", "Haridwar", "Roorkee", "Haldwani"],
    WB: ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Howrah"]
};
